import type { KGQuality, KGStats, OntologyAudit } from "../../lib/kg-api";
import type { DataQualitySnapshot } from "./page";

const stats: KGStats = {
  total_nodes: 547761,
  total_edges: 1302476,
  total_entities: 1850237,
  node_tables: 62,
  rel_tables: 73,
  nodes_by_type: {
    KnowledgeUnit: 185455,
    LegalClause: 83443,
    LegalDocument: 54865,
    DocumentSection: 42252,
    LawOrRegulation: 39651,
    RegulationClause: 29655,
    MindmapNode: 28526,
    Classification: 28035,
    HSCode: 22976,
    TaxRate: 9000,
    CPAKnowledge: 7371,
    TaxClassificationCode: 4205,
    TaxCodeDetail: 4061,
    TaxCodeIndustryMap: 1380,
    FAQEntry: 1156,
    IndustryRiskProfile: 720,
    RegionalTaxPolicy: 620,
    AuditTrigger: 463,
    RiskIndicatorV2: 463,
    IssuingBody: 398,
    AccountingEntry: 375,
    SpreadsheetEntry: 280,
    BusinessActivity: 204,
    AccountRuleMapping: 200,
    TaxRiskScenario: 180,
    ChartOfAccount: 159,
    AccountingSubject: 159,
    Penalty: 127,
    ChartOfAccountDetail: 123,
    FilingFormV2: 121,
    FormTemplate: 109,
    TaxIncentiveV2: 109,
    TaxIncentive: 109,
    IndustryKnowledge: 102,
    ComplianceRuleV2: 84,
    TaxRateMapping: 80,
    TaxCalculationRule: 73,
    TaxCreditIndicator: 55,
    AccountingStandard: 43,
    TaxRateDetail: 37,
    Region: 31,
    TaxWarningIndicator: 30,
    Industry: 24,
    TaxRateSchedule: 23,
    DepreciationRule: 21,
    TaxpayerRatePolicy: 20,
    TaxPolicy: 20,
    FTIndustry: 19,
    TaxType: 19,
    TaxEntity: 17,
    CrossSellTrigger: 17,
    DeductionStandard: 13,
    ChurnIndicator: 12,
    ServiceCatalog: 12,
    CustomerProfile: 12,
    TaxCalendar: 12,
    AccountEntry: 10,
    IndustryBookkeeping: 7,
    EnterpriseType: 6,
    EntityTypeProfile: 6,
    TaxpayerStatus: 5,
    TaxExemptionThreshold: 1,
  },
};

const quality: KGQuality = {
  total_nodes: 363102,
  total_edges: 1014862,
  edge_density: 2.795,
  title_coverage: 99.6,
  content_coverage: 51.0,
  tables_checked: 0,
  quality_score: 100,
  grade: "A",
  details: [
    {
      severity: "medium",
      type: "unlabeled_edge_targets",
      message: "111 MENTIONS edges point to nodes without readable labels",
    },
  ],
};

const audit: OntologyAudit = {
  schema_source: "/home/kg/cognebula-enterprise/schemas/ontology_v4.2.cypher",
  canonical_count: 35,
  live_count: 83,
  brooks_ceiling: 37,
  over_ceiling: true,
  over_ceiling_by: 46,
  intersection: [
    "AccountingStandard",
    "AccountingSubject",
    "AuditTrigger",
    "BusinessActivity",
    "Classification",
    "ComplianceRule",
    "FilingForm",
    "IssuingBody",
    "KnowledgeUnit",
    "LegalClause",
    "LegalDocument",
    "Penalty",
    "Region",
    "RiskIndicator",
    "TaxCalculationRule",
    "TaxEntity",
    "TaxIncentive",
    "TaxRate",
    "TaxType",
  ],
  missing_from_prod: [
    "DeductionRule",
    "FilingFormField",
    "FinancialIndicator",
    "FinancialStatementItem",
    "IndustryBenchmark",
    "InvoiceRule",
    "JournalEntryTemplate",
    "PolicyChange",
    "ResponseStrategy",
    "SocialInsuranceRule",
    "TaxAccountingGap",
    "TaxBasis",
    "TaxItem",
    "TaxLiabilityTrigger",
    "TaxMilestoneEvent",
    "TaxTreaty",
  ],
  rogue_in_prod: [
    "AccountEntry",
    "AccountRuleMapping",
    "AccountingEntry",
    "ArrowFunction",
    "CPAKnowledge",
    "ChartOfAccount",
    "ChartOfAccountDetail",
    "ChurnIndicator",
    "Class",
    "Community",
    "ComplianceRuleV2",
    "CrossSellTrigger",
    "CustomerProfile",
    "DeductionStandard",
    "DepreciationRule",
    "Document",
    "DocumentSection",
    "EnterpriseType",
    "EntityTypeProfile",
    "External",
    "FAQEntry",
    "FTIndustry",
    "File",
    "FilingFormV2",
    "FilingObligation",
    "Folder",
    "FormTemplate",
    "Function",
    "HSCode",
    "Industry",
    "IndustryBookkeeping",
    "IndustryKnowledge",
    "IndustryRiskProfile",
    "Interface",
    "LawOrRegulation",
    "LifecycleActivity",
    "LifecycleStage",
    "Method",
    "MindmapNode",
    "RegionalTaxPolicy",
    "RegulationClause",
    "RiskIndicatorV2",
    "Section",
    "ServiceCatalog",
    "SpecialZone",
    "SpreadsheetEntry",
    "TaxCalendar",
    "TaxClassificationCode",
    "TaxCodeDetail",
    "TaxCodeIndustryMap",
    "TaxCreditIndicator",
    "TaxExemptionThreshold",
    "TaxIncentiveV2",
    "TaxPlanningStrategy",
    "TaxPolicy",
    "TaxRateDetail",
    "TaxRateMapping",
    "TaxRateSchedule",
    "TaxRateVersion",
    "TaxRiskScenario",
    "TaxWarningIndicator",
    "TaxpayerRatePolicy",
    "TaxpayerStatus",
    "Topic",
  ],
  rogue_buckets: {
    v1_v2_bleed: ["ComplianceRuleV2", "FilingFormV2", "FormTemplate", "RiskIndicatorV2", "TaxIncentiveV2"],
    duplicate_clusters: {
      tax_rate: ["TaxCodeIndustryMap", "TaxRateDetail", "TaxRateMapping", "TaxRateSchedule", "TaxpayerRatePolicy"],
      accounting: ["AccountEntry", "AccountRuleMapping", "AccountingEntry", "ChartOfAccount", "ChartOfAccountDetail", "DepreciationRule"],
      industry: ["FTIndustry", "Industry", "IndustryBookkeeping", "IndustryKnowledge", "IndustryRiskProfile"],
      policy: ["RegionalTaxPolicy", "TaxExemptionThreshold", "TaxPolicy"],
    },
    saas_leak: ["ChurnIndicator", "CrossSellTrigger", "CustomerProfile", "EnterpriseType", "EntityTypeProfile", "ServiceCatalog"],
    legacy: ["CPAKnowledge", "DocumentSection", "FAQEntry", "HSCode", "MindmapNode", "TaxClassificationCode", "TaxCodeDetail"],
    other: [
      "ArrowFunction",
      "Class",
      "Community",
      "DeductionStandard",
      "Document",
      "External",
      "File",
      "FilingObligation",
      "Folder",
      "Function",
      "Interface",
      "LawOrRegulation",
      "LifecycleActivity",
      "LifecycleStage",
      "Method",
      "RegulationClause",
      "Section",
      "SpecialZone",
      "SpreadsheetEntry",
      "TaxCalendar",
      "TaxCreditIndicator",
      "TaxPlanningStrategy",
      "TaxRateVersion",
      "TaxRiskScenario",
      "TaxWarningIndicator",
      "TaxpayerStatus",
      "Topic",
    ],
  },
  verdict: "FAIL",
  severity: "high",
};

export const PROD_SNAPSHOT_FIXTURE: DataQualitySnapshot = {
  stats,
  quality,
  audit,
};
